# pylint: disable=missing-module-docstring,pointless-statement
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl-3).
{
    "name": "Quoter - Service Configuration",
    "summary": "Cotizador de servicios profesionales con productos por nivel de complejidad",
    "author": "Calyx Servicios S.A.",
    "maintainers": ["YourName"],
    "website": "https://odoo.calyx-cloud.com.ar/",
    "license": "AGPL-3",
    "category": "Sales",
    "version": "15.0.6.6.23",
    "development_status": "Beta",
    "application": True,
    "installable": True,
    "depends": [
        "base",
        "web",
        "sale",
        "sale_management",
        "product",
        "stock",
        # Después de sale_order_type: el create del quoter corre antes que el de OCA
        # y deja name=Q antes de next_by_id (evita consumir la secuencia del tipo en vano).
        "sale_order_type",
        "report_custom",
    ],
    "data": [
        "security/quoter_groups.xml",
        "security/quoter_admin_groups.xml",
        "security/ir.model.access.csv",
        "security/quoter_security_rules.xml",
        "security/quoter_sale_order_access_rules.xml",
        "data/quoter_product_category_data.xml",
        "data/sequence_data.xml",
        "data/quoter_branch_data.xml",
        "data/pricelist_data.xml",
        "data/quoter_product_attribute.xml",
        "views/quoter_generic_product_wizard_views.xml",
        "views/quoter_adjustment_note_wizard_views.xml",
        "views/quoter_bulk_add_lines_wizard_views.xml",
        "data/quoter_formula_view_cleanup.xml",
        "views/quoter_service_views.xml",
        "views/quoter_product_level_range_views.xml",
        "views/quoter_product_views.xml",
        "views/quoter_product_menu_views.xml",
        "views/sale_order_views.xml",
        "reports/quoter_quotation_report.xml",
        "views/quoter_sale_order_workflow_views.xml",
        "views/quoter_menu.xml",
        "views/quoter_settings_views.xml",
        "views/quoter_formula_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "quoter/static/src/scss/quoter_matrix.scss",
            "quoter/static/src/js/quoter_tab_labels.js",
            "quoter/static/src/js/quoter_preserve_active_record.js",
            "quoter/static/src/js/quoter_area_block_embed.js",
            "quoter/static/src/js/quoter_bulk_add_lines.js",
            "quoter/static/src/js/quoter_range_columns.js",
            "quoter/static/src/js/quoter_separator_styles.js",
            "quoter/static/src/js/quoter_area_hours_matrix.js",
            "quoter/static/src/js/quoter_formula_matrix.js",
            "quoter/static/src/js/quoter_chain_matrix.js",
        ],
        "web.assets_qweb": [
            "quoter/static/src/xml/tax_totals.xml",
        ],
    },
}
